### ISSUE TITLE
usage Information is not complete

### ISSUE THREAD

**Issue by sotiriszegiannis** [simsek97/simsCheckbox#1]
In order for this component to work font awesome and bootstrap is required besides the simsCheckbox js and css.
This is a working code:

`<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">	
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
	 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link href="simsCheckbox.css" rel="stylesheet"/>	
    <script src="simsCheckbox.js"></script>`

**Comment by simsek97** [comment]
That is sure correct. Thanks

**Comment by sotiriszegiannis** [comment]
Try an empty page with just jquery and your two files the css and the js and it doesn't work.I tried it many times.
